name: reto_seek
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  pigeon: ^22.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # local
  core:
    path: ./modules/core
  qr_code:
    path: ./modules/qr_code
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.3.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png

  fonts:
  - family: Oswald
    fonts:
      - asset: assets/fonts/Oswald-Regular.ttf
      - asset: assets/fonts/Oswald-Bold.ttf
        weight: 700
      - asset: assets/fonts/Oswald-Light.ttf
        weight: 300
  - family: PublicSans
    fonts:
      - asset: assets/fonts/PublicSans-Regular.ttf
      - asset: assets/fonts/PublicSans-ExtraBold.ttf
        weight: 700
      - asset: assets/fonts/PublicSans-light.ttf
        weight: 300
  - family: ReadexPro
    fonts:
      - asset: assets/fonts/ReadexPro-Medium.ttf
      - asset: assets/fonts/ReadexPro-Regular.ttf
        weight: 300
      - asset: assets/fonts/ReadexPro-Bold.ttf
        weight: 700