name: qr_code
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  skeletonizer: ^1.4.2
  
  core:
    path: ../core
  ui:
    path: ../ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0